[package]
name = "insidejob"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web= { version="^4", features=["openssl"]}
openssl = { version = "0.10" }
uuid = { version="^1", features=["v4", "fast-rng", "macro-diagnostics"]}
lazy_static = "^1.4"
reedline="^0.14"